

export const SET_ACCESS_TOKEN = 'USER/ACCESS_TOKEN'
export const SET_USERID = 'USER/SET_USERID'
export const SET_USER_NAME = 'USER/SET_USER_NAME'

export const SET_USER_ROLE = 'USER/SET_USER_ROLE'
export const SET_NICK_NAME = 'USER/SET_NICK_NAME'

